apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:/1hS6rNFI1lKSlF+BauylNX8P4awpa8+YK097pLyZs+UDmJm7xaIIw==,iv:cyIF0aflt0Bbdd3K38RGrxuVWduAo87mNVA+3nYR+Ew=,tag:QGJYDRiNfncLL81+chWqsA==,type:str]
sops:
    age:
        - recipient: age137504yr9n8n7acr49una4m4jyk9fet36jsnlct0su6vf9v5zyvesznvz6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NXViWFJKUWE1TVh6Y1dU
            S0FWdU5ldnp1N1AySXZ0cUdRMitpUkNvK1FFCnNsSlc1NUtGMktScFcvSGVRUXVN
            RVRTck45Z0RmYVVTU2IwNmxEUWc2eWsKLS0tIGd2SFFGVk90REVkOGRrU1ZRK3Ar
            MlJrM3pRSlh1NThpbXI2bCs0WXZFK1kK08hrJwrEqV+6q+R1CbtYzolYivgWllY6
            gj7G38OcQvSDfTtU22E0H2hYfVb3avDE7vL/iiBvjtaeI81tgM5duA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T16:27:40Z"
    mac: ENC[AES256_GCM,data:f+Nh/d6Etxj6CfzBCDr5/j+Zn3eFThhiufTZ2NpEIOnCK+iRM6v92XUylZderoK8ar7RmQ10K5aycL2w6TzD8aFXkTi4LtpYtPYmZEcRdRZXKx1nokKHYX6wL4K/ETg+EO43AEE94N1cLX0SJyYbf4P05let5fY+AUjumOXZyX0=,iv:lHYgEK+PAYkI1jGhQbTTDMTGVjv/KdGm0yrpyJwmmVE=,tag:gwBlJJoS8xqkCC5bC19oiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
