apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cert-manager-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - cloudflare-api-token-secret.secret.sops.yaml
